baseURL = "/"
languageCode = "nl-BE"
title = "Fablab Lier"
theme = "ananke"
DefaultContentLanguage= "nl"
sectionPagesMenu = "main"
summaryLength = 10

[params]
  featured_image = "/img/header.jpg"
  custom_css = ["/css/style.css"]
  # site_logo = "/img/logo-fablab.png"
